# Generated by Django 4.2.4 on 2023-11-17 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_name_contact2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
